### ISSUE TITLE
Nuxt 3 with nuxi/vite support

### ISSUE THREAD

**Issue by jcwieme** [wattanx/nuxt-bundle-analysis#18]
Hi, there,

I was looking for a solution to automate the bundle size check with Github and came across your repo.

I had a look and unfortunately I can't setup with Nuxt 3 under Vite. I don't think it's supported.

I've tried to adapt the `build/analyze` settings to Vite ([doc](https://github.com/btd/rollup-plugin-visualizer#options)):

```
  build: {
    analyze: {
      template: 'raw-data',
      open: false,
    },
  },
```

Are you planning to make a solution for Vite or have I misconfigured the plugin?

Thanks for your feedback!

**Comment by wattanx** [comment]
Currently vite is not supported.
We are thinking about supporting it, but it will take time to release it.
